version: '2'

services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: SLKAHDLvashjdFGJKHFGSADGHFASFDGASDFHJGA
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: SLKAHDLvashjdFGJKHFGSADGHFASFDGASDFHJGA
    volumes:
      - ./mysql:/var/lib/mysql
    restart: unless-stopped

  wp:
    image: wordpress:fpm-alpine
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: SLKAHDLvashjdFGJKHFGSADGHFASFDGASDFHJGA
    depends_on:
      - db
    volumes:
      - ./wordpress:/var/www/html
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./wordpress:/var/www/html
    ports:
      - '80:80'
    depends_on:
      - wp
    restart: unless-stopped
